CREATE DATABASE srdbsclientdb;

CREATE USER srdbsclient;

GRANT ALL PRIVILEGES ON srdbsclientdb.* TO 'srdbsclient'@'127.0.0.1' IDENTIFIED BY 'password';

USE srdbsclientdb;

DROP TABLE SP_FILE;
DROP TABLE FULL_FILE;

DROP TABLE SP_FILE;
DROP TABLE FULL_FILE;

CREATE TABLE FULL_FILE(
	F_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FNAME VARCHAR(100),
	FSIZE BIGINT,
	HASHVALUE VARCHAR(100),
	UP_DATE VARCHAR(100)
);


CREATE TABLE SP_FILE(
    SP_FILE_ID INT NOT NULL AUTO_INCREMENT,
    F_ID INT,
    SP_FILENAME VARCHAR(400),
    F_SIZE BIGINT,
    HASHVALUE VARCHAR(200),
    REF_CLOUD_ID INT,
    RAID_REF INT,
    REMOTE_PATH VARCHAR(400),

    CONSTRAINT PK_SP_FILEID_1 PRIMARY KEY(SP_FILE_ID),
    CONSTRAINT FK_SP_FILEID_2 FOREIGN KEY (F_ID) REFERENCES FULL_FILE (F_ID)
);

SELECT  * FROM SP_FILE; SELECT  * FROM FULL_FILE;
